name: Update and Sync Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Type of version bump (patch, minor, major)"
        required: true
        default: "patch"

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Load current version from environment variable
      - name: Load Current Version
        id: load_version
        run: echo "CURRENT_VERSION=${{ secrets.BUILD_VERSION }}" >> $GITHUB_ENV

      # Step 3: Increment version with npm version
      - name: Increment Version with npm
        id: increment_version
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_type }}"
          NEW_VERSION=$(npm version $VERSION_TYPE --no-git-tag-version)

          echo "New Version: $NEW_VERSION"
          # Remove the 'v' prefix if npm version outputs it
          CLEANED_VERSION=${NEW_VERSION#v}
          echo "CLEANED_VERSION=$CLEANED_VERSION" >> $GITHUB_ENV

      # Step 4: Commit and Push the Changes
      - name: Commit and Push Version Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "Bump version to $CLEANED_VERSION"
          git push origin dev

      # Step 5: Update GitHub Environment Variable
      - name: Update GitHub Environment Variable
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.updateEnvironmentVariable({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: "production",  # Replace with your environment name
              name: "APP_VERSION",
              value: process.env.CLEANED_VERSION
            })