name: Update and Sync Version

on:
  workflow_dispatch:
     inputs:
       version_type:
         description: "Type of version bump (patch, minor, major)"
         required: true
         default: "patch"

jobs:
  update-version:
    runs-on: main

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        run: echo "${{ secrets.BUILD_VERSION }}" >> $GITHUB_ENV

      # Step 2: Load current version from environment variable
      - name: Load Current Version
        id: load_version
        run: echo "CURRENT_VERSION=${{ secrets.BUILD_VERSION }}" >> $GITHUB_ENV

      # Step 3: Increment version with npm version
      - name: Increment Version with npm
        id: increment_version
        run: |
          
          # Increment the version in package.json and package-lock.json
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          
          # Clean the 'v' prefix if present
          CLEANED_VERSION=${NEW_VERSION#v}
          echo "New Version: $CLEANED_VERSION"
          echo "CLEANED_VERSION=$CLEANED_VERSION" >> $GITHUB_ENV

      # Step 4: Commit and Push the Changes
      - name: Commit and Push Version Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "Bump version to $CLEANED_VERSION"
          git push origin main
