name: TestSync Version

on:
  workflow_dispatch:
     inputs:
       version_type:
         description: "Type of version bump (patch, minor, major)"
         required: true
         default: "patch"

jobs:
  update-version:
    runs-on: main

    steps:
      # Step 1: Checkout the repository
      - name: Check Version
        run: echo "CURRENT_VERSION=${{ secrets.BUILD_VERSION }}" >> $GITHUB_ENV
