name: Update Version and Sync

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Type of version bump (patch, minor, major)"
        required: true
        default: "patch"
        
  
jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure the Node.js version matches your project

      # Step 4: Increment version using npm version
      - name: Increment Version with npm
        id: increment_version
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_type }}"
          
          # Increment the version in package.json and package-lock.json
          NEW_VERSION=$(npm version $VERSION_TYPE --no-git-tag-version)
          

      # Step 5: Commit and Push the Changes
      - name: Commit and Push Changes
        run: |
          cd version-change
          ls
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "Bump version to $NEW_VERSION"
          git push origin main

